## Graphs

- A graph G = (V, E) consists of a set of vertices (nodes) V and a set of edges E

<img src="assets/graph1.png">

Use examples:
- Vertices are cities and edges are flights
    - Find the best route between cities
- Vertices are classes, edges connect classes whose schedules overlap 
    - Want to find feasible schedules for a student -- i.e. find the node with least connections
- Vertice are objects in memory, edges connect objects that refer to each other
    - Want to know when an object can be freed

### Directed Graphs (Digraphs)
- Edges have directions associated with them

<img src="assets/digraph.png">

### Weighted Graphs
- There is a *weight* associated with each edge
<br>
<br>
<img src="assets/weighted_graph.png"> 

### Terminology:
- Vertex `v1` is *adjacent* to vertex `v2` if an edge connects `v1` and `v2`
    - There exists an edge `e = (v1, v2) in E`
<br>

- A *path* is a sequence of vertices in which each vertex is adjacent to the next one
    - `p = (v1, ..., vn)` s.t. `(v_i, v_i+1) in E`
    - The length of the path is the number of edges in it
<br>

- A *cycle* in a path is a sequence `(v1, ..., vn) s.t. (v_i, v_i+1) in E` and `(vn, v1) in E`
<br>

- A graph with no cycles is an *acyclic graph*
- A *DAG* is a directed acyclic graph

- A *simple path* is a path with no repetition of vertices
- A *simple cycle* is a cycle with no repetition of vertices
- Two vertices are *connected* if there is a path between them
- A subset of vertices is a connected component of G if each pair of vertices in the subset are connected
- The *degree* over vertex `v` is the number of edges associated with `v`


## Stacks (ADT)
- LIFO (last in, first out)
- A collection of elements
- Operations: `push` and `pop`
    - `push`: put an element in the stack
    - `pop`: Get the last element that was put onto the stack, and then remove the element



In [ ]:
class Stack:
    def __init__(self):
        self.data = []

    def push(self, elem: int):
        self.data.append(elem)

    def pop(self):
        return self.data.pop()
    
if __name__ == '__main__':
    s = Stack()
    s.push(5)
    s.push(10)
    print(s.pop())
    s.push(15)
    print(s.pop())

## Graph ADT

#### Adjacency Matrix (representing a graph in memory)
An `n * n` matrix where `M[i][j] = 1` if there is an edge between `vi` and `vj`, and 0 otherwise 

<img src="assets/adj_matrix1.png"> 
<img src="assets/adj_matrix2.png"> 

In [5]:
import numpy as np

'''
Idea: Store a matrix inside of a graph object, access the matrix when querying edges
'''

class Graph:
    def __init__(self, num_nodes: int):
        self.adj_matrix = np.zeros([num_nodes, num_nodes])

    def is_edge(self, i, j): #is connected
        return self.adj_matrix[i][j] == 1

    def put_edge(self, i, j): 
        self.adj_matrix[i][j] = 1

    def remove_edge(self, i, j):
        self.adj_matrix[i][j] = 0

if __name__ == '__main__':
    graph = Graph(4)
    graph.put_edge(1, 2)
    print(graph.is_edge(1, 2))

    print(graph.adj_matrix)

True
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Adjacency List

Adjacency lists store the nodes and their neighbours as linked lists:
- For `n = |V|` vertices, `n` linked lists. The `i`<sup>th</sup> is a list of vertices adjacent to `vi`

<img src="assets/adj_list1.png"> 
<img src="assets/adj_list2.png"> 

In [ ]:
'''
- Have the same kind of functions as we have in Graph
- Want to represent the data using adjacency list

- For each node, keep a list of its neighbours (i.e. nodes connected to it)
- Use Linked Lists in order to store the neighbours

i.e. 
    1
   /  \
2       3

1: 2->3 (could also be 3->2)
2: 1
3: 1

Design: Python list of LLs and nodes
- nodes[i] is the LL that contains the neighbours of i
- degree d --> the largest possible number of neighbours any node could have
'''
from typing import List, Any

class Node:
    def __init__(self, data: Any):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, idx: int, data: Any):
        new_node = Node(data)
        
        if self.head is None:
            self.head = new_node
        else:
            if idx == 0:
                # Using a swap to insert a new node on the head
                self.head, self.head.next = new_node, self.head
            else:
                # Find the end of the linked list to insert the new node
                cur = self.head
                for _ in range(idx - 1):
                    cur = cur.next
                
                # Need cur.next = new_node, new_node.next = cur.next (to insert)
                cur.next, new_node.next = new_node, cur.next

    def is_in(self, data: int) -> bool:
        cur = self.head
        while cur is not None:

            if cur.data == data:
                return True
            cur = cur.next
        return False
    
    def remove(self, data: int):
        # Remove the first node with data = data in the list
        if self.head.data == data:
            self.head = self.head.next
            return 
        else:
            cur = self.head
            while cur.next is not None and cur.next.data != data:
                cur = cur.next
            
            if cur.next is None:
               raise Exception("Error trying to remove", data)

            cur.next = cur.next.next 

    def print(self):
        cur = self.head

        while cur is not None:
            print(cur.data, "-> ", end = "")
            cur = cur.next

        print("None")

class AdjacencyList:
    def __init__(self, num_nodes: int):
        self.nodes: List[LinkedList] = []

        for _ in range(num_nodes):
            self.nodes.append(LinkedList())

    def is_edge(self, i, j):
        # self.nodes[i] is the list of the neighbours of node i
        return self.nodes[i].is_in(j)
    
    def put_edge(self, i, j): #O(1)
        self.nodes[i].insert(0, j)

    def remove_edge(self, i, j): #O(d)
        self.nodes[i].remove(j)
        '''
        NOTE:
        if user is allowed to call put_edge(1, 2) twice, need to either
        take care of it inside put_edge or inside remove_edge
        '''

if __name__ == '__main__':
    LL = LinkedList()
    LL.insert(0, 123)
    LL.insert(0, 125)
    LL.print()

125 -> 123 -> None


### Time Complexity

- Operations:
    - Checking for an edge between `vi` and `vj`:
        - Adjacency Matrix: `O(1)`
        - Adjacency List: `O(d)`
            - d: The maximum degree in the graph (max number of edges that goes out of the node)
    - Finding all vertices adjacent to `vi`
        - Adjacency Matrix: `O(|V|)`
            - `|V|`: The number of vertices in the graph
        - Adjacency List: `O(d)`

### Space Requirements
- Adjacency Matrix: `O(|V|`<sup>2</sup>`)`
    - Need to store `|V|`<sup>2</sup> matrix entries
- Adjacency List: `O(|V| + |E|)`
    - Need to store `|V|` linked lists. Collectively, the linked list contains `|E|` entries, so the space requirement is `a`<sub>1</sub>`|V|` + `a`<sub>2</sub>`|E|`, which is `O(|V| + |E|)`

## Graph Traversal
- Want to visit (ex: in order to print) each vertex exactly once

<img src="assets/graph_traversal.png"> 

### Algorithm:
```python
while (there are non-visited nodes):
    initialize data structure DS
    Add a non-visited vertex vi to DS
    Mark vi as visited
    while (DS is not empty):
        Remove vj from DS
        Mark vj as visited
        Add non-visited vertices adjacent to vj to DS
```

### Breadth-First Traversal
- Used when DS is a **QUEUE**

<img src="assets/BFT.png"> 

### Depth-First Traversal
- Used when DS is a **STACK**

<img src="assets/DFT.png"> 

### Recursive Depth-First Traversal
```python
DFS(vi)
    Mark vi as visited
    
    for each non-visited vertex vj adjacent to vi:
        DFS(vj)
```