### Q1

In [1]:
%%file 2021.c

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

char* concat_all(char **strs, int strs_sz0) {
    //concatenate all strs_sz strings in strs, and return the resultant string
    char *all = (char *)malloc(strs_sz0 * 3 * sizeof(char)); //Three chars per string
    
    for (int i = 0; i < strs_sz0; i++) {
        strcat(all, strs[i]);
    }

    return all;
}

int main(void) {
    char *strs[] = {"ESC", "MAT", "MSE", "CIV"};
    char *all = concat_all(strs, 4); 
    printf("%s\n", all); //ESCMATMSECIV
    free(all);
    return 0;
}

Overwriting 2021.c


In [2]:
%%bash
gcc 2021.c -g -o 2021
./2021

ESCMATMSECIV


## Q2

Write a C program that takes in an array of strings and the number of strings in the array, and returns 1 if there are repetitions in the array, and 0 otherwise.

The function *must* run in average O(n) time, where n is the number of strings and must use hashing.
The function siganture must be:


int repeats(char **strs, int strs_sz);


Briefly justify why the function runs in O(n) overage time in the comments.

In [ ]:
%%file 2021.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


int in_visited(char *str, char **visited, int visited_count) {
    for (int i = 0; i < visited_count; i++) {
        if (strcmp(str, visited[i]) == 0) {
            return 0;
        }
    }

    return -1;
}

int repeats(char **strs, int strs_sz) {
    char **visited = (char **)malloc(strs_sz * 3 * sizeof(char *));
    int repeated = 0;
    int visited_count = 0;

    for (int i = 0; i < strs_sz; i++) {
        if (in_visited(strs[i], visited, visited_count) == 0) {
            repeated++;
        } else {
            visited[i] = (char *)malloc(strlen(strs[i]) + 1);
            strcpy(visited[i], strs[i]);
            visited_count++;
        }
    }

    return repeated;
}

int main() {
    char *strs1[] = {"ESC", "MAT", "MSE", "CIV"};
    printf("%d\n", repeats(strs1, 4)); // 0

    char *strs2[] = {"ESC", "MAT", "MSE", "CIV", "ESC"};
    printf("%d\n", repeats(strs2, 5)); // 1
}


Overwriting 2021.c


In [19]:
%%bash
gcc 2021.c -g -o 2021
./2021

0
1


## Problem 3

A BST is defined as follows
```python
class BST:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

    def insert(self, value):
        '''
        node.insert(5) is the same as BST.insert(node, 5)
        We use this when recursively calling, e.g. self.left.insert
        '''
        if value < self.value:
            if self.left == None:
                self.left = BST(value)
            else:
                self.left.insert(value)
        else:
            if self.right == None:
                self.right = BST(value)
            else:
                self.right.insert(value)

    def __repr__(self):
        '''The string representation of a node.
        Here, we convert the value of the node to a string and make that
        the representation.
        We can now use
        a = BST(4)
        print(a) # prints 4
        '''
        return str(self.value)
```

  Write a function

  def third_largest(node)

  that finds the value of the third-largest element in the BST. The function must run in O(h) time, where h is the height
  of the BST rooted in node.

  Sample autograder case:
  root = BST(1)
  root.insert(2)
  root.insert(3)
  third_largest(root) # 1

  Submit Q3.py, which should contain the (unaltered)definition of the BST, and the implementation of the function third_largest(node)

In [22]:
class BST:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

    def insert(self, value):
        '''
        node.insert(5) is the same as BST.insert(node, 5)
        We use this when recursively calling, e.g. self.left.insert
        '''
        if value < self.value:
            if self.left == None:
                self.left = BST(value)
            else:
                self.left.insert(value)
        else:
            if self.right == None:
                self.right = BST(value)
            else:
                self.right.insert(value)

    def __repr__(self):
        '''The string representation of a node.
        Here, we convert the value of the node to a string and make that
        the representation.
        We can now use
        a = BST(4)
        print(a) # prints 4
        '''
        return str(self.value)
    
def third_largest(node):
    '''
    find the value of the third-largest element in the BST. The function must run in O(h) time, where h is the height
    of the BST rooted in node.
    '''
    result = {"count": 0, "value": None}
    
    def reverse_in_order(current):
        if current is None or result["count"] >= 3:
            return

        # Visit right subtree first (larger values)
        reverse_in_order(current.right)

        # Visit current node
        result["count"] += 1
        if result["count"] == 3:
            result["value"] = current.value
            return

        # Visit left subtree (smaller values)
        reverse_in_order(current.left)

    reverse_in_order(node)
    return result["value"]

if __name__ == '__main__':

  # Sample autograder case:
    root = BST(10)
    root.insert(5)
    root.insert(15)
    root.insert(2)
    root.insert(5)
    root.insert(13)
    root.insert(22)
    root.insert(14)

    print(third_largest(root))  # Should print the third largest value
# 1

14


## Question 5:

In this problem, you will write a funciton that computes a particular definition of a distance
between two lists, using dynamic programming, and returns the set of transformations that
correpond to that distance.

A element can be transformed by
1) Substituting one element with another 
2) adding an element
3) removing an element

The distance between two lists is the number of transformations required to transform one
list into another. For example, the distance between [1, 1, 2, 3] and [2, 2, 3] is 2:
[1, 1, 2, 3] (remove element) ->  [1, 2, 3] -> (substitute 1 with 2) -> [2, 2, 3].

The elements of the list are given in a particular order. [1, 2, 3] and [3, 2, 1] are 
not the same list.   

To solve this problem using dynamic programming, for lists L1 and L2, define a 2-D array D s.t.
D[i][j] is the distance between L[:i] and L[:j].

Hint: 
D[i][0] = i, since it takes i removals to get from L[:i] to the empty list.
    

Part A
======

Write the function with the signature

def construct_D_arr(L1, L2)

which returns the 2D array D, such that D[i][j] is the distance between L1[:i] and L2[:j]. 

For example, construct_D_arr([1, 2], [1, 3]) should return 

D = [[0, 1, 2],
    [1, 0, 1],
    [2, 1, 1]]

Your algorithm must be of complexity O(mn) where m = len(L1) and n = len(L2)

Part B
======

Write a function 
def min_dist(L1, L2)

which returns a length of the shortest sequences of transformations from L1 to L2.

For example, min_dist(L1, L2) should return 1 since there is only one substitution needed in
the sequence [1, 2]->[1, 3].


Your algorithm must be of complexity O(mn) where m = len(L1) and n = len(L2)

Part C
======

Write a function 

def recover_path(L1, L2)

which returns the shortest path between L1 and L2 via substitutions, deletions, and additions. For example,
recover_path([1, 2], [1, 3]) can return

[[1, 2], [1, 3]]

(If there are multiple possible paths, return one of them.)

In [ ]:
from typing import List
import numpy as np

def construct_D_arr(L1, L2) -> np.ndarray:
    '''
    D[i][j] is distance between L1[:i], L2[:j]

    [1, 2], [1, 3]

    [[0,1,2],
    [1,0,1 ],
    [2,_,_ ]]
    a) L1[:0], L2[:0] = 1 -> 1 = 0 (same)
    b) L1[:0], L2[:1] = 1 -> [1, 3] = 1 (remove 3)
    c) L1[:1], L2[:0] = [1, 2] -> 1 = 1 (remove 2)
    d) L1[:1], L2[:1] = [1, 2] -> [1, 3] = 1 (substituting 3 with 2)
    '''
    D = np.zeros((len(L1)+1, len(L2)+1), dtype=int)

    for i in range(len(L1)+1):
        D[i][0] = i
    
    for j in range(len(L2)+1):
        D[0][j] = j

    for i in range(1, len(L1)+1):
        for j in range(1, len(L2)+1):
            if L1[i - 1] == L2[j - 1]:
                D[i][j] = D[i - 1][j - 1]
            else:
                D[i][j] = min(
                    D[i - 1][j - 1] + 1,  # substitution
                    D[i][j - 1] + 1,      # insertion
                    D[i - 1][j] + 1       # deletion
                )
                
    return D

    
print(construct_D_arr([1, 2], [1, 3]))

[[0 1 2]
 [1 0 1]
 [2 1 1]]
